version: 2.1

# @param trigger-message: A summary message of what triggered the pipeline to run
# set when triggering pipelines in flipDevTools::TriggerRevDepPipelines() step
# @param remote-deps: A comma-separated string of GitHub refs, which can
# be used to install specific branches of dependencies; used by both
# flipDevTools::InstallDeps() and TriggerRevDepPipelines;
# e.g. "Displayr/flipU@DS-4300,cran/survey@4.0"
# @param plugins-branch String specifying a branch of the Displayr/Plugins
# repo to trigger a build in (if the workflow is a success), the default "" does not
# trigger a build in Plugins
# @param triggered-packages: A comma-separated string of reverse depenendency
# packages which have already been triggered, i.e. should be excluded (not triggered)
# by TriggerRevDepPipelines() in the Trigger reverse dependencies step; it is updated
# automatically by that function to ensure each package is triggered at most once.
parameters:
    trigger-message:
        type: string
        default: ""
    remote-deps:
        type: string
        default: ""
    plugins-branch:
        type: string
        default: ""
    triggered-packages:
        type: string
        default: ""

orbs:
  r-packages: displayr/r-packages@dev:b2ea38c223590ec06889ead88409ef2547b8275d

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build-and-check-package:
          name: BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
      - r-packages/deploy-package:
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          filters:
            branches:
              only:
                - master
      - r-packages/trigger-revdeps:
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          plugins-branch: << pipeline.parameters.plugins-branch >>
          trigger-message: << pipeline.parameters.trigger-message >>
          triggered-packages: << pipeline.parameters.triggered-packages >>
