name: Build flipAPI

on:
  workflow_dispatch:
  push:
  workflow_call: {}

jobs:
  build:
    name: Build flipAPI
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@DPI-2964-add-package-ci
    with:
      installable-path: pkgs.${currentSystem}.rPackages.flipAPI
      build-args: --override-input displayr-flipAPI .
    secrets: inherit
